### ISSUE TITLE
Some problems that is not in the DJ2 modpack

### ISSUE THREAD

**Issue by ghost** [ByThePowerOfScience/DivineJourney2Addons#4] opened 2023-06-01 03:04 UTC
I'm trying to use DJ2Addon in my own modpack (I know this is not reconmmanded) and found a bug related to modular magic,it seem that it only support 1.4.0 version.
Here's the crash report when I tried to run with modular magic 1.6.0.
https://mclo.gs/J9E3wT9
If you don't want to fix this, it's ok, I can use an older version, thanks。

**Comment by ByThePowerOfScience** [comment] 2023-08-20 14:08
That's odd.  It should only be running that Mixin if that class is present, so there shouldn't be any reason for it to throw this error.
I'll look into it.

**Comment by ByThePowerOfScience** [comment] 2023-11-10 20:22
@mczph Does this issue still occur in the new beta release?  I made this mod to be usable in non-DJ2 packs, so I'd like to fix the problem if it's still happening.

**Comment by ghost** [comment] 2023-11-11 02:21
> @mczph Does this issue still occur in the new beta release?  I made this mod to be usable in non-DJ2 packs, so I'd like to fix the problem if it's still happening.

Will go for testing.  

PS: After some time, I am now using [mmce](https://www.curseforge.com/minecraft/mc-mods/modularmachinery-community-edition) (it is a fork version of modular machinery, which has optimized and added a lot of content, and has incorporated modular magic related content in the latest version).

**Comment by ghost** [comment] 2023-11-11 09:25
@ByThePowerOfScience It seems that the new version works very well. The only problem is that it has a forced dependency on AgriCraft, which causes Industrial Foregoing to crash. I removed this entry in mixins.dj2addons.json and everything went fine. Here is the crash report:https://mclo.gs/9x3Dak5

**Comment by ByThePowerOfScience** [comment] 2023-11-19 22:44
> @ByThePowerOfScience It seems that the new version works very well. The only problem is that it has a forced dependency on AgriCraft, which causes Industrial Foregoing to crash. I removed this entry in mixins.dj2addons.json and everything went fine. Here is the crash report:https://mclo.gs/9x3Dak5

I'll take a look, thanks!

**Comment by ByThePowerOfScience** [comment] 2023-12-04 11:47
@mczph I'm unable to reproduce the issue.  Can you try again and make sure you're using the latest version of DJ2Addons and have removed any older versions from your `mods` directory?

**Comment by ghost** [comment] 2023-12-10 03:59
@ByThePowerOfScience Yes,I'm using the latest version.Maybe my description is not clear enough, the following is the smallest list of reproducible modlist.
![image](https://github.com/ByThePowerOfScience/DivineJourney2Addons/assets/103164772/2b1ed44b-9395-448a-94fb-b6611ec42a1f)
crash report:https://mclo.gs/fVJBFgH
After enabing AgriCraft and its dependency,the game will run normally.
I think a check for whether the game has AgriCraft installed should be added to prevent this issue

**Comment by ByThePowerOfScience** [comment] 2023-12-13 18:42
MixinBooter is currently not supported due to some compatibility issues on their part, which is subject to change.  Try removing MixinBooter and testing with [MixinBootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap) instead.

**Comment by ghost** [comment] 2023-12-15 14:28
@ByThePowerOfScience I have tested it and the same problem occurred.Can you please have a look on if there is a hard dependency on AgriCraft,thank you.

**Comment by ByThePowerOfScience** [comment] 2024-01-17 20:20
> @ByThePowerOfScience I have tested it and the same problem occurred.Can you please have a look on if there is a hard dependency on AgriCraft,thank you.

I have, and I've tested it several times in several different mod configurations.  I'm just not able to encounter the error.

Closing this as CNR for now. If more people have this issue, I'll reopen it.

**Closed as completed by ByThePowerOfScience** 2024-01-17 20:20 UTC
Labels: bug, non-DJ2
